### ISSUE TITLE
How to Set-i Network Card Parameters in Windows System

### ISSUE THREAD

**Issue by ghost** [malfunkt/arpfox#6]
C:\Users\help\Downloads>arpfox_windows_amd64.exe -t 172.16.15.0/24 -i 172.16.15.3
2019/01/21 21:53:41 Could not use interface 172.16.15.3: route ip+net: no such network interface。I don't know how Windows can get the name of the network card interface and set the - I parameter to the local IP address.
How to Set-i Network Card Parameters in Windows System，How to Configure Under Windows.

**Comment by sxueck** [comment]
If the author does not update, please use the modified repository.
https://github.com/sxueck/arpfox

**Comment by xiam** [comment]
I pushed a new release: https://github.com/malfunkt/arpfox/releases/tag/v0.9.9, you can use `ipconfig` to see the device name, try with: `-i "Wi-Fi"`. Thanks @sxueck!

**Comment by xiam** [comment]
And, with the latest version you can use `arpfox -l` to list all available interfaces.
